version: 0.2

phases:
  install:
    commands:
      - yarn install 

  pre_build:
    commands:
      - yarn jest

artifacts:
  files:
    - 'src/**'  # Save all files generated during the build, can be refined further
  discard-paths: yes  # Save artifacts in the root of the S3 bucket (no subfolders)

cache:
  paths:
    - node_modules/**  # Cache dependencies to speed up subsequent builds
